import { Tool } from './types';

export const TOOLS_DATA: Tool[] = [
  // --- WIDEO ---
  {
    id: '1',
    name: 'PixVerse AI',
    categories: ['Wideo'],
    tagline: 'Twórz realistyczne wideo i animacje postaci z tekstu.',
    description: 'Potężny generator wideo specjalizujący się w spójności ruchu i teksturach. Oferuje funkcje "Magic Brush" do animowania wybranych fragmentów zdjęcia. Idealny do tworzenia klipów w stylu anime lub realistycznym.',
    tutorialStep: '1. Wpisz prompt opisujący scenę. 2. Załaduj zdjęcie (opcjonalnie). 3. Wybierz styl (Anime/Realistic).',
    pricing: 'Freemium',
    rating: 8,
    ctaLink: 'https://pixverse.ai',
    icon: '🎬',
    tags: ['Motion', 'Anime'],
  },
  {
    id: '2',
    name: 'Higgsfield AI',
    categories: ['Wideo'],
    tagline: 'Kinowa kontrola kamery i postaci w Twoim telefonie.',
    description: 'Narzędzie mobile-first stworzone przez inżynierów Snapchata. Unikalny model "Diffuse" pozwala zmieniać ubrania lub tło bez naruszania postaci.',
    tutorialStep: 'Pobierz appkę, użyj funkcji "Remix" na wideo z galerii, zmień konkretny element promptem.',
    pricing: 'Subscription',
    rating: 8.5,
    ctaLink: 'https://higgsfield.ai',
    icon: '📱',
    tags: ['Mobile', 'Remix'],
  },
  {
    id: '3',
    name: 'Hailuo AI',
    categories: ['Wideo'],
    tagline: 'Płynne wideo 6s (Director Model).',
    description: 'Chiński gigant generujący wideo w jakości 1080p. Oferuje klipy do 6 sekund o niesamowitej płynności i realizmie, konkurujący z Sora.',
    tutorialStep: 'Zaloguj się, wybierz model T2V-02, wpisz szczegółowy prompt kinowy.',
    pricing: 'Free',
    rating: 8,
    ctaLink: 'https://hailuoai.com',
    icon: '🐉',
    tags: ['Beta', 'High-Res'],
    isHot: true
  },
  {
    id: '30',
    name: 'Kling AI',
    categories: ['Wideo'],
    tagline: 'Realistyczne wideo z fizyką świata rzeczywistego.',
    description: 'Największy konkurent Sora dostępny publicznie. Potrafi generować długie sekwencje (do 2 minut w wersji Pro) z niesamowitym zachowaniem fizyki ciał i płynów.',
    tutorialStep: 'Wybierz text-to-video, opisz ruch kamery i oświetlenie.',
    pricing: 'Freemium',
    rating: 9.5,
    ctaLink: 'https://klingai.com',
    icon: '🎥',
    tags: ['Physics', 'Long Video'],
    isNew: true
  },
  {
    id: '4',
    name: 'HeyGen',
    categories: ['Wideo', 'Produktywność'],
    tagline: 'Profesjonalne awatary mówiące w 175 językach.',
    description: 'Platforma do tworzenia wideo biznesowych bez kamery. Idealna do szkoleń i marketingu. Oferuje Video Translation z lip-sync.',
    tutorialStep: 'Wybierz awatar, wpisz tekst scenariusza, wybierz język i wygeneruj.',
    pricing: 'Freemium',
    rating: 10,
    ctaLink: 'https://heygen.com',
    icon: '👔',
    tags: ['Business', 'Avatars'],
  },
   {
    id: '19',
    name: 'Runway Gen-3',
    categories: ['Wideo'],
    tagline: 'High-end Generative Video dla profesjonalistów.',
    description: 'Zaawansowany model wideo oferujący precyzyjną kontrolę nad czasem, ruchem kamery i strukturą wideo.',
    tutorialStep: 'Użyj Motion Brush do kontroli ruchu, zdefiniuj klatki kluczowe.',
    pricing: 'Paid',
    rating: 9,
    ctaLink: 'https://runwayml.com',
    icon: '🎞️',
    tags: ['Pro', 'Cinema'],
  },

  // --- GRAFIKA ---
  {
    id: '22',
    name: 'Leonardo.ai',
    categories: ['Grafika'],
    tagline: 'Artystyczna kontrola i własne modele "Fine-Tuned".',
    description: 'Jeden z najbardziej zaawansowanych generatorów obrazu. Pozwala na trenowanie własnych modeli na spójnych postaciach oraz oferuje niesamowite funkcje "Image Guidance".',
    tutorialStep: 'Wybierz model "Phoenix", ustaw "Image Guidance" dla pozy postaci i generuj.',
    pricing: 'Freemium',
    rating: 9.5,
    ctaLink: 'https://leonardo.ai',
    icon: '🦁',
    tags: ['Game Assets', 'Training'],
    isHot: true
  },
  {
    id: '23',
    name: 'Gemini (Google)',
    categories: ['Produktywność', 'Grafika', 'Wideo', 'Dev'],
    tagline: 'Multimodalny ekosystem: Nano Banana & Veo.',
    description: 'Flagowy model Google. Zawiera w sobie "Nano Banana" (Imagen 3) do fotorealistycznej grafiki oraz "Veo" do generowania wideo wysokiej jakości. Głęboka integracja z Workspace.',
    tutorialStep: 'Wpisz: "Stwórz fotorealistyczny obraz..." lub użyj @Gems aby stworzyć własnego bota.',
    pricing: 'Freemium',
    rating: 9.5,
    ctaLink: 'https://gemini.google.com',
    icon: '💎',
    tags: ['Multimodal', 'Nano Banana', 'Veo'],
    isHot: true
  },
  {
    id: '29',
    name: 'ImageFX / MusicFX',
    categories: ['Grafika', 'Audio'],
    tagline: 'Eksperymentalne studio kreatywne od Google Labs.',
    description: 'Kreatywny plac zabaw wykorzystujący model Imagen 3. Interfejs oparty na "Expressive Chips" pozwala szybko podmieniać słowa kluczowe i eksperymentować ze stylem.',
    tutorialStep: 'Wejdź na labs.google, wybierz ImageFX i klikaj w "Chips" aby zmieniać elementy obrazu.',
    pricing: 'Free',
    rating: 9,
    ctaLink: 'https://labs.google/fx/tools/image-fx',
    icon: '🧪',
    tags: ['Labs', 'Creative'],
    isNew: true
  },
  {
    id: '5',
    name: 'Midjourney',
    categories: ['Grafika'],
    tagline: 'Król artystycznego AI i fotorealizmu.',
    description: 'Benchmark jakości grafik AI. Wersja v6 oferuje niesamowite światło, tekstury i kompozycję. Działa na Discordzie i web.',
    tutorialStep: 'Wpisz /imagine + opis. Użyj --v 6.0 dla najlepszej jakości.',
    pricing: 'Paid',
    rating: 10,
    ctaLink: 'https://midjourney.com',
    icon: '🎨',
    tags: ['Art', 'Discord'],
  },
  {
    id: '6',
    name: 'Ideogram',
    categories: ['Grafika'],
    tagline: 'Grafiki z idealnym tekstem i typografią.',
    description: 'Jeśli potrzebujesz logo, plakatu lub grafiki z napisem, Ideogram jest bezbłędny tam, gdzie inni zawodzą. Teraz w wersji 2.0 z jeszcze lepszym realizmem.',
    tutorialStep: 'Wpisz prompt zawierający tekst w cudzysłowie, np. "Poster saying Hello World".',
    pricing: 'Freemium',
    rating: 9.5,
    ctaLink: 'https://ideogram.ai/welcome',
    icon: '🔤',
    tags: ['Typography', 'Logos'],
    isHot: true
  },
  {
    id: '26',
    name: 'Craiyon',
    categories: ['Grafika'],
    tagline: 'Darmowy generator "Dla Ludu" (Dawne DALL-E Mini).',
    description: 'Całkowicie darmowe, proste narzędzie do szybkiego generowania konceptów. Nie oferuje jakości Midjourney, ale jest świetne do szybkich szkiców i memów.',
    tutorialStep: 'Wpisz cokolwiek, odczekaj chwilę na 9 wariacji obrazu.',
    pricing: 'Free',
    rating: 6.5,
    ctaLink: 'https://www.craiyon.com/en',
    icon: '🖍️',
    tags: ['Free', 'Sketch'],
  },
  {
    id: '7',
    name: 'Photoroom',
    categories: ['Grafika'],
    tagline: 'Magiczne studio fotograficzne dla e-commerce.',
    description: 'Automatycznie usuwa tło i generuje profesjonalne scenerie produktowe. Niezbędnik dla sprzedawców online.',
    tutorialStep: 'Wgraj zdjęcie produktu -> Wybierz "AI Background" -> Pobierz.',
    pricing: 'Freemium',
    rating: 10,
    ctaLink: 'https://photoroom.com',
    icon: '🛍️',
    tags: ['E-commerce', 'Remove BG'],
  },
  {
    id: '8',
    name: 'Krea.ai',
    categories: ['Grafika', 'Wideo'],
    tagline: 'Generowanie i poprawianie jakości w czasie rzeczywistym.',
    description: 'Rysuj kształty, a AI zamieni je w zdjęcia na żywo. Funkcja "Enhancer" naprawia rozmyte grafiki i zwiększa rozdzielczość. Posiada też generator wideo.',
    tutorialStep: 'Wgraj niewyraźne zdjęcie do Enhancera lub rysuj na canvasie w trybie Real-time.',
    pricing: 'Freemium',
    rating: 9,
    ctaLink: 'https://krea.ai',
    icon: '✨',
    tags: ['Real-time', 'Upscale'],
  },

  // --- DEV ---
  {
    id: '27',
    name: 'Manus',
    categories: ['Dev', 'Produktywność'],
    tagline: 'Autonomiczny agent, który buduje aplikacje za Ciebie.',
    description: 'Przyszłość programowania. Manus to nie tylko czat - to agent, który przejmuje kontrolę nad środowiskiem, instaluje pakiety i rozwiązuje złożone problemy inżynieryjne.',
    tutorialStep: 'Zaproś Manusa do repozytorium i wydaj polecenie: "Zrefaktoryzuj ten moduł i napisz testy".',
    pricing: 'Paid',
    rating: 10,
    ctaLink: 'https://manus.im',
    icon: '🦾',
    tags: ['Agent', 'Autonomous'],
    isNew: true,
    isHot: true
  },
  {
    id: '25',
    name: 'AI Studio (Google)',
    categories: ['Dev'],
    tagline: 'Najszybszy sposób na budowanie z Gemini API.',
    description: 'Narzędzie dla deweloperów do testowania promptów, multimodalnych inputów (wideo/audio) i eksportu kodu bezpośrednio do Twojej aplikacji.',
    tutorialStep: 'Wgraj wideo, zadaj pytanie modelowi, kliknij "Get Code".',
    pricing: 'Free',
    rating: 9.5,
    ctaLink: 'https://aistudio.google.com',
    icon: '🛠️',
    tags: ['API', 'Prototyping'],
  },
  {
    id: '31',
    name: 'v0.dev',
    categories: ['Dev', 'Grafika'],
    tagline: 'Generuj interfejsy UI (React/Tailwind) w sekundę.',
    description: 'Narzędzie od Vercel. Opisz interfejs, a v0 wygeneruje piękny, gotowy do użycia kod React Components (Shadcn UI + Tailwind).',
    tutorialStep: 'Wpisz "Dashboard dla SaaS z dark mode", skopiuj kod.',
    pricing: 'Freemium',
    rating: 10,
    ctaLink: 'https://v0.dev',
    icon: '📐',
    tags: ['UI/UX', 'React'],
    isNew: true
  },
  {
    id: '9',
    name: 'Bolt.new',
    categories: ['Dev'],
    tagline: 'Zbuduj i opublikuj pełną aplikację jednym promptem.',
    description: 'Środowisko deweloperskie w przeglądarce. Piszesz "Zrób stronę pizzerii", a on pisze kod, instaluje biblioteki i stawia serwer.',
    tutorialStep: 'Opisz aplikację -> Edytuj w czacie -> Kliknij "Deploy".',
    pricing: 'Freemium',
    rating: 10,
    ctaLink: 'https://bolt.new',
    icon: '⚡',
    tags: ['Fullstack', 'WebContainer'],
    isHot: true
  },
  {
    id: '10',
    name: 'Cursor AI',
    categories: ['Dev'],
    tagline: 'Edytor kodu przyszłości (Fork VS Code).',
    description: 'Edytor kodu, który "rozumie" cały Twój projekt. Funkcja "Tab" przewiduje całe bloki kodu, a "Composer" edytuje wiele plików naraz.',
    tutorialStep: 'Zainstaluj, zaimportuj projekt z VS Code, naciśnij Cmd+K aby edytować kod.',
    pricing: 'Freemium',
    rating: 10,
    ctaLink: 'https://cursor.sh',
    icon: '🖱️',
    tags: ['IDE', 'Coding'],
  },
  {
    id: '20',
    name: 'Claude 3.5 Sonnet',
    categories: ['Dev', 'Produktywność'],
    tagline: 'Najlepszy model do logiki i kodowania.',
    description: 'Model od Anthropic, który przewyższa inne w zadaniach programistycznych i niuansach językowych. Posiada funkcję "Artifacts" do podglądu kodu.',
    tutorialStep: 'Wklej fragment kodu i poproś o refaktoryzację lub wyjaśnienie błędu.',
    pricing: 'Freemium',
    rating: 10,
    ctaLink: 'https://claude.ai',
    icon: '🧠',
    tags: ['LLM', 'Reasoning'],
  },
  {
    id: '11',
    name: 'Framer',
    categories: ['Dev', 'Grafika'],
    tagline: 'Design, który staje się stroną www (No-Code).',
    description: 'Narzędzie dla designerów. Projektujesz jak w Figmie, a klikając "Publish" masz gotową, responsywną stronę z animacjami.',
    tutorialStep: 'Zaprojektuj layout, dodaj breakpointy, kliknij Publish.',
    pricing: 'Freemium',
    rating: 9,
    ctaLink: 'https://framer.com',
    icon: '📐',
    tags: ['No-Code', 'Design'],
  },
  {
    id: '12',
    name: 'Tiiny.host',
    categories: ['Dev'],
    tagline: 'Opublikuj stronę w 3 sekundy (Drag & Drop).',
    description: 'Najprostszy hosting pod słońcem. Przeciągasz plik HTML/ZIP i otrzymujesz link. Idealny do szybkiego demo.',
    tutorialStep: 'Spakuj pliki strony do ZIP -> Przeciągnij na stronę Tiiny -> Gotowe.',
    pricing: 'Freemium',
    rating: 8,
    ctaLink: 'https://tiiny.host',
    icon: '🌐',
    tags: ['Hosting', 'Simple'],
  },

  // --- PRODUKTYWNOŚĆ ---
  {
    id: '24',
    name: 'GenSpark',
    categories: ['Produktywność'],
    tagline: 'Wyszukiwarka generująca "Sparkpages".',
    description: 'Zamiast listy linków, GenSpark tworzy dla Ciebie dedykowaną stronę one-page na dany temat, agregując wiedzę, wideo i obrazy z sieci.',
    tutorialStep: 'Wpisz "Najlepsze rowery gravelowe 2025" i otrzymaj gotowy poradnik zakupowy.',
    pricing: 'Free',
    rating: 9,
    ctaLink: 'https://www.genspark.ai',
    icon: '🎇',
    tags: ['Search', 'Sparkpages'],
    isNew: true
  },
  {
    id: '28',
    name: 'Prompt Cowboy',
    categories: ['Produktywność', 'Dev'],
    tagline: 'Narzędzia do inżynierii promptów.',
    description: 'Zestaw narzędzi dla "zaklinaczy AI". Pomaga optymalizować, zarządzać i testować prompty, aby wycisnąć maksimum z modeli LLM.',
    tutorialStep: 'Wklej swój prompt i użyj narzędzi optymalizacji, aby zmniejszyć zużycie tokenów.',
    pricing: 'Freemium',
    rating: 8.5,
    ctaLink: 'https://www.promptcowboy.ai',
    icon: '🤠',
    tags: ['Prompt Engineering', 'Utils'],
    isNew: true
  },
  {
    id: '21',
    name: 'ChatGPT (4o)',
    categories: ['Produktywność', 'Dev'],
    tagline: 'Wszechstronny asystent multimodalny.',
    description: 'Najpopularniejszy chatbot świata. Widzi, słyszy i mówi. Idealny do każdego zadania od pisania po analizę danych.',
    tutorialStep: 'Zapytaj o cokolwiek lub wgraj plik do analizy.',
    pricing: 'Freemium',
    rating: 10,
    ctaLink: 'https://chatgpt.com',
    icon: '🤖',
    tags: ['General', 'Assistant'],
  },
  {
    id: '13',
    name: 'Wispr Flow',
    categories: ['Produktywność'],
    tagline: 'Mów, a AI napisze to lepiej niż Ty.',
    description: 'Zaawansowane dyktowanie. Zamienia chaotyczne myśli w idealnie sformatowane e-maile i notatki. Działa w każdej aplikacji (Mac).',
    tutorialStep: 'Naciśnij skrót klawiszowy, mów swobodnie, AI wstawi sformatowany tekst.',
    pricing: 'Freemium',
    rating: 8,
    ctaLink: 'https://flow.wispr.ai',
    icon: '🎙️',
    tags: ['Dictation', 'Mac'],
  },
  {
    id: '14',
    name: 'Perplexity AI',
    categories: ['Produktywność'],
    tagline: 'Wyszukiwarka, która daje odpowiedzi, nie linki.',
    description: 'Zastępuje Google. Zadajesz pytanie, a AI przeszukuje internet i pisze syntetyczny raport ze źródłami.',
    tutorialStep: 'Zadaj pytanie jak człowiekowi. Przełącz na tryb "Pro" dla głębszego researchu.',
    pricing: 'Freemium',
    rating: 10,
    ctaLink: 'https://perplexity.ai',
    icon: '🔍',
    tags: ['Search', 'Research'],
    isHot: true
  },
  {
    id: '15',
    name: 'NotebookLM',
    categories: ['Produktywność'],
    tagline: 'Twój osobisty asystent researchu z podcastem.',
    description: 'Wgraj PDFy, notatki i linki. AI odpowie na pytania z Twoich źródeł, a nawet wygeneruje podcast (Audio Overview) omawiający materiał.',
    tutorialStep: 'Stwórz notatnik, dodaj źródła, kliknij "Audio Overview" aby posłuchać.',
    pricing: 'Free',
    rating: 10,
    ctaLink: 'https://notebooklm.google.com',
    icon: '📓',
    tags: ['Study', 'Google'],
  },
  {
    id: '16',
    name: 'Gamma App',
    categories: ['Produktywność', 'Grafika'],
    tagline: 'Prezentacje, dokumenty i strony w minutę.',
    description: 'Koniec z męczeniem się w PowerPoint. Wpisz temat, a Gamma stworzy slajdy, układ i grafiki. Teraz obsługuje też import dokumentów.',
    tutorialStep: 'Wybierz "Presentation", wpisz temat, wybierz szablon wizualny.',
    pricing: 'Freemium',
    rating: 9.5,
    ctaLink: 'https://gamma.app',
    icon: '📊',
    tags: ['Slides', 'Office'],
  },
  {
    id: '32',
    name: 'DeepSeek',
    categories: ['Dev', 'Produktywność'],
    tagline: 'Najtańsza potęga open-source.',
    description: 'Model V3/R1, który wstrząsnął rynkiem. Oferuje jakość zbliżoną do GPT-4 za ułamek ceny. Świetny do kodowania i matematyki.',
    tutorialStep: 'Użyj przez API lub czat webowy do analizy dużych zbiorów danych.',
    pricing: 'Free',
    rating: 9.5,
    ctaLink: 'https://deepseek.com',
    icon: '🐋',
    tags: ['Open Source', 'Math'],
    isNew: true
  },

  // --- AUDIO ---
  {
    id: '17',
    name: 'ElevenLabs',
    categories: ['Audio'],
    tagline: 'Najbardziej realistyczne głosy AI na świecie.',
    description: 'Klonowanie głosu i Text-to-Speech, którego nie odróżnisz od człowieka. Polski język działa perfekcyjnie.',
    tutorialStep: 'Wpisz tekst, wybierz głos (np. Adam) i kliknij Generate.',
    pricing: 'Freemium',
    rating: 10,
    ctaLink: 'https://elevenlabs.io',
    icon: '🗣️',
    tags: ['TTS', 'Voice Clone'],
  },
  {
    id: '18',
    name: 'Suno / Udio',
    categories: ['Audio'],
    tagline: 'Stwórz radiowy hit w 30 sekund.',
    description: 'Generatory piosenek (tekst + wokal + muzyka). Potrafią stworzyć utwór w dowolnym stylu od Jazzu po Techno.',
    tutorialStep: 'Wpisz opis piosenki, np. "Upbeat 80s synthwave about coding".',
    pricing: 'Freemium',
    rating: 9,
    ctaLink: 'https://suno.com',
    icon: '🎵',
    tags: ['Music', 'Generation'],
  }
];